FROM node:20-alpine

WORKDIR /app

# Install dependencies required for bcrypt
RUN apk add --no-cache make gcc g++ python3 git

COPY package*.json ./

# Install dependencies with rebuild of bcrypt
RUN npm install
RUN npm rebuild bcrypt --build-from-source

COPY . .

RUN npx prisma generate

EXPOSE 59243

CMD ["npm", "run", "dev"]