version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "59243:59243"
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
      - prisma-data:/app/prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_SECRET=restaurant-notebook-secret-key
      - NEXTAUTH_URL=http://localhost:59243
      - OPENAI_API_KEY=sk-mock-key-for-development
      - NEXT_PUBLIC_FIREBASE_API_KEY=mock-firebase-key
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=mock-domain.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=mock-project-id
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=mock-storage-bucket.appspot.com
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=123456789
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:123456789:web:abcdef123456
      - PUSHER_APP_ID=mock-pusher-app-id
      - NEXT_PUBLIC_PUSHER_KEY=mock-pusher-key
      - PUSHER_SECRET=mock-pusher-secret
      - NEXT_PUBLIC_PUSHER_CLUSTER=eu
      - NEXT_PUBLIC_SENTRY_DSN=https://mock-sentry-dsn@o123456.ingest.sentry.io/123456
      - NEXT_PUBLIC_LOGROCKET_APP_ID=restaurant-notebook/dev
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
    restart: unless-stopped

volumes:
  node_modules:
  prisma-data: